#!/bin/sh
# Usage: GeneHitCounter BreakpointAnalyzer-file file.gff3

BPAFILE=bpexons.txt
GFF=/home/shokin/genomes/Zm-B73-REFERENCE-GRAMENE-4.0/Zm00001d.2.gff3

java -cp "build/install/evanslab-java/lib/*" edu.carnegiescience.dpb.evanslab.GeneHitCounter $BPAFILE $GFF 
