#!/bin/sh
./gradlew run --args="pollen-on-silk/W22.d10.Q10.vcf.gz pollen-on-silk/remapped_B73_W22.gene.gff3 pollen-on-silk/Zea_mays.B73_RefGen_v4.41.gene.gff3 pollen-on-silk/B73.d10.Q10.vcf.gz 10 0.5 0.1 0.9"
