#!/bin/sh
SNPDIR=/home/shokin/EvansLab/ig1/GBS/results/4.SNP_VarDetect
PREFIX=VT
SUFFIX=avinput.variant_function.snp

java -server -cp "build/install/evanslab-java/lib/*" edu.carnegiescience.dpb.evanslab.SNPSegregation $SNPDIR $PREFIX $SUFFIX 1 48 49 96 $1
